- name: ensure cockpit plugin dir exists
  file:
    path: /usr/local/share/cockpit/faros
    state: directory
    mode: 0755
  register: install

- name: install cockpit plugin
  copy:
    src: "{{ item }}"
    dest: "/usr/local/share/cockpit/faros/{{ item }}"
    mode: 0644
  loop:
    - index.html
    - manifest.json
  when: install is changed

- name: add links to cockpit - insert
  lineinfile:
    path: /usr/local/share/cockpit/faros/index.html
    line: <li><a href="{{ item.url }}" target="_blank">{{ item.name }}</a></li> <!-- {{ item.icon }} -->
    insertafter: <!-- ##START## -->
    regexp: "{{ item.name }}"
  loop: "{{ cockpit_links }}"
  when: cockpit_links_action == 'insert'

- name: add links to cockpit - append
  lineinfile:
    path: /usr/local/share/cockpit/faros/index.html
    line: <li><a href="{{ item.url }}" target="_blank">{{ item.name }}</a></li> <!-- {{ item.icon }} -->
    insertbefore: <!-- ##END## -->
    regexp: "{{ item.name }}"
  loop: "{{ cockpit_links }}"
  when: cockpit_links_action == 'append'

- name: remove links from cockpit
  lineinfile:
    path: /usr/local/share/cockpit/faros/index.html
    line: <li><a href="{{ item.url }}" target="_blank">{{ item.name }}</a></li> <!-- {{ item.icon }} -->
    state: absent
    regexp: "{{ item.name }}"
  loop: "{{ cockpit_links }}"
  when: cockpit_links_action == 'delete'
