#!/usr/bin/env ansible-playbook
- name: configure the hypervisor
  hosts: bastion_hosts
  gather_facts: yes
  become: yes

  roles:
    - name: hypervisor

- name: configure virtual machines
  hosts: virtual
  gather_facts: no
  become: no

  roles:
    - name: virtual-machine
      virtual_machine_hypervisor: '{{ groups.bastion_hosts.0 }}'
      virtual_machine_network: bridge=farosbr0
      virtual_machine_disk: size=100,format=qcow2
