#!/usr/bin/env ansible-playbook

- name: deploy openshift load balancer
  hosts: bastion_hosts
  gather_facts: yes
  become: yes

  roles:
    - name: loadbalancer

  post_tasks:
    - name: create cockpit links
      include_role:
        name: cockpit-links
      vars:
        cockpit_links:
          - name: Load Balancer Stats
            url: "http://{{ inventory_hostname }}.{{ cluster_name }}.{{ cluster_domain }}:8080/stats"
            icon: pficon-route
