- name: get current nextserver settings
  shell: >
    uci get {{ item.key }} || echo 'NOVALUE'
  loop:
    - key: dhcp.@dnsmasq[0].tftp_root
      target: /tftpboot
    - key: dhcp.@dnsmasq[0].dhcp_boot
      target: pxelinux.0,{{ inventory_hostname }},{{ ansible_host }}
  loop_control:
    label: "{{ item.key }}"
  register: dhcp_lkp
  changed_when: no
  delegate_to: dhcp
  become: no

- name: update nextserver settings
  shell: |
    uci set {{ item.item.key }}="{{ item.item.target }}"
    uci commit dhcp
  loop: "{{ dhcp_lkp.results }}"
  loop_control:
    label: "{{ item.item.key }} = {{ item.item.target }}"
  when: item.stdout != item.item.target
  changed_when: yes
  notify: commit changes
  delegate_to: dhcp
  become: no
