- name: check for requirements
  assert:
    that:
      - ansible_os_family == 'RedHat' or
        ansible_os_family == 'CentOS'
      - ansible_distribution_major_version == '7' or
        ansible_distribution_major_version == '8'
    fail_msg: "Bastion host does not meet requirements"
    success_msg: "Bastion host meets requirements."

- import_tasks: tftp.yaml

- import_tasks: http.yaml
