#!/usr/bin/env ansible-playbook
- name: configure dhcp entry
  block:
    - name: look for existing records
      shell: >
        uci show dhcp |
        grep "{{ dhcp_mac_address | lower }}" |
        grep -Eo '@host\[\d+\]'
      register: dhcp_id
      changed_when: False
      delegate_to: dhcp

    - name: read existing records
      shell: uci get dhcp.{{ dhcp_id.stdout }}.{{ item.key }}
      loop:
        - key: name
          target: "{{ dhcp_name }}"
        - key: ip
          target: "{{ dhcp_ip }}"
        - key: dns
          target: "1"
      loop_control:
        label: "{{ item.key }}"
      register: dhcp_record
      when: dhcp_id is not failed
      changed_when: False
      delegate_to: dhcp

    - name: update existing records
      shell: |
        uci set dhcp.{{ dhcp_id.stdout }}.{{ item.item.key }}={{ item.item.target }}
        uci commit
      when: item.stdout != item.item.target
      loop: "{{ dhcp_record.results }}"
      loop_control:
        label: "{{ item.item.key }} = {{ item.item.target }}"
      changed_when: True
      notify: commit changes
      delegate_to: dhcp

  rescue:
    - name: create new record
      shell: |
        uci add dhcp host
        uci set dhcp.@host[-1].name="{{ dhcp_name }}"
        uci set dhcp.@host[-1].mac="{{ dhcp_mac_address | lower }}"
        uci set dhcp.@host[-1].ip="{{ dhcp_ip }}"
        uci set dhcp.@host[-1].dns="1"
        uci commit
      changed_when: True
      notify: commit changes
      delegate_to: dhcp

